package org.lightframework.http.api;

/**
 * TODO: Generated by IntelliJ IDEA.
 *
 * @author luochuan
 */
public enum HttpMethod {
    OPTIONS,
    GET,
    HEAD,
    POST,
    PUT,
    DELETE,
    TRACE,
    CONNECT,
    PATCH
}
